# The name of the file equals the name of the profile

label: I18N_OPENXPKI_UI_PROFILE_USER_LABEL

validity:
    notafter: +0006
 
style:
    00_user_basic_style:
        label: I18N_OPENXPKI_UI_PROFILE_BASIC_STYLE_LABEL
        description: I18N_OPENXPKI_UI_PROFILE_BASIC_STYLE_DESC
        ui:
            subject:
                - username
                - realname
                - department
                - email
            info:
                - comment

        subject: 
            dn: CN=[% realname %]+UID=[% username %][% IF department %],DC=[% department %][% END %],DC=Test Deployment,DC=OpenXPKI,DC=org
            san: 
               email: "[% email.lower %]"

        metadata:
            requestor: "[% realname %]"
            email: "[% email %]"
            department: "[% department %]"

# Profile extensions - set 0/1 as needed
# Also see sections defined in default.yaml
extensions:
    key_usage:
        critical: 1
        digital_signature: 1
        non_repudiation:   1
        key_encipherment:  1
        data_encipherment: 0
        key_agreement:     0
        key_cert_sign:     0
        crl_sign:          0
        encipher_only:     0
        decipher_only:     0

    extended_key_usage:
        critical: 1
        client_auth:      1
        server_auth:      0
        email_protection: 1
        codeSigning:      0
        timeStamping:     0
        # MS Smartcard Logon
        1.3.6.1.4.1.311.20.2.2: 1
 
   
# Define the input fields you used below here or in template.yaml
#template:


