# trunk/package/debian/core
#

TOPDIR=../../../..
SRCBASE=$(TOPDIR)/trunk/perl-modules/core/trunk
PACKAGE=libopenxpki-perl
PERLNAME=OpenXPKI
PKGDIR=../deb/core

# Makefile.inc contains common settings for all packages (checked in)
include ../Makefile.inc
# Makefile.local may be used locally to override settings (not checked in)
-include ../Makefile.local

