requires 'Archive::Zip'                  => 0;
requires 'CGI::Fast'                     => '2.10';
requires 'CGI::Session'                  => '3.95';
requires 'CGI'                           => '4.21';
requires 'Class::Std'                    => '0.0.8';
requires 'Config::Merge'                 => '1';
requires 'Config::Std'                   => 0;
requires 'Config::Versioned'             => 0;
requires 'Connector'                     => '1.08';
requires 'Crypt::CBC'                    => '2.29';
requires 'Crypt::OpenSSL::AES'           => '0.02';      # for e.g. OpenXPKI::Crypto::VolatileVault
requires 'Crypt::PKCS10'                 => '1.8';
requires 'Crypt::SMIME'                  => '0.15';
requires 'Data::Password'                => '1.07';
requires 'Data::Serializer'              => '0.44';
requires 'Data::UUID'                    => 0;           # for OpenXPKI::Template::Plugin::Utils and CPAN
requires 'Date::Parse'                   => '0';
requires 'DateTime::Format::DateParse'   => '0.04';
requires 'DateTime::Format::Strptime'    => 0;           # for OpenXPKI::Server::Workflow::Persister::DBI
requires 'DateTime'                      => '0.22';
requires 'DBD::Mock'                     => '1.45';
requires 'DBD::SQLite'                   => '1.52';      # for tests of OpenXPKI::Server::Database
requires 'DBI'                           => '1';
requires 'DBIx::Handler'                 => '0.14';      # for OpenXPKI::Server::Database
requires 'Devel::NYTProf'                => 0;           # for CPAN
requires 'English'                       => '1';         # for broken Perl installations like on Ubuntu Drapper
requires 'Exception::Class'              => '1.22';
requires 'HTML::Entities'                => 0;
requires 'IO::Prompt'                    => '0.099004';  # for deployment tools
requires 'JSON'                          => 0;
requires 'Locale::gettext_pp'            => 0;
requires 'Log::Log4perl'                 => '0.51';
requires 'LWP::UserAgent'                => '6.05';      # Constituent of module  libwww-perl
requires 'Math::BigInt'                  => '1.9993';    # makes FreeBSD happy
requires 'MIME::Entity'                  => 0;
requires 'Module::Load'                  => '0.32';      # for OpenXPKI::Server::Database
requires 'Moose'                         => '1';
requires 'MooseX::Params::Validate'      => '0.21';      # for OpenXPKI::Server::Database
requires 'Net::DNS'                      => '0.83';
requires 'Net::LDAP'                     => '0.32';
requires 'Net::Server'                   => '0.94';
requires 'NetAddr::IP'                   => 0;
requires 'Params::Validate'              => '0.77';
requires 'Proc::ProcessTable'            => '0.43';
requires 'Proc::SafeExec'                => '1.4';
requires 'Regexp::Common'                => '2';
## requires 'RT::Client::REST::Ticket'      => '0'; CURRENTLY OPTIONAL
## requires 'RT::Client::REST'              => '0'; CURRENTLY OPTIONAL
requires 'SOAP::Lite'                    => 0;
requires 'SQL::Abstract::More'           => '1.28';      # for OpenXPKI::Server::Database
requires 'Sub::Exporter'                 => 0;           # for OpenXPKI::Server::Database::Util
requires 'Sys::SigAction'                => '0.06';
requires 'Template'                      => '2.15';
requires 'Test::More'                    => '0.98';
requires 'Test::Pod::Coverage'           => '1.00';
requires 'Test::Pod'                     => '1.00';
requires 'Text::CSV_XS'                  => '0.23';
requires 'Time::HiRes'                   => '1';
requires 'Workflow'                      => '0.27';
requires 'XML::Simple'                   => '1';
