# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# To add local overrides, create the file Vagrantfile.local. Example:
#
#   config_values[:mirror] = ENV['HOME'] + '/Data/mirrors'

Vagrant.configure("2") do |config|

#    config_values = {}

#    if File.file?('Vagrantfile.local')
#        external = File.read 'Vagrantfile.local'
#        eval external
#    end
    local_vagrantfile = 'Vagrantfile.local'
    @localcfg = {}
    if File.exist?(local_vagrantfile)
        load local_vagrantfile
    end

  # Every Vagrant virtual environment requires a box to build off of.
  #config.vm.box = "openxpki/wheezy-alldeps"  
  config.vm.box = "debian/jessie64"

#  if config_values[:mirrors]
#    config.vm.synced_folder config_values[:mirrors], "/mirrors"
#  end

 # config.vm.define "build", primary: true do |build|
 #     config.vm.hostname = "build"
 #     config.vm.provision :shell, :path => "provision-build.sh"
 #     config.vm.synced_folder "../..", "/code-repo"
 # end

  # Default VM - testing on debian jessie 
  config.vm.define "test", primary:true do |test|
      config.vm.hostname = "oxi-test-jessie"
      config.vm.provision :shell, :path => "provision-test.sh"
      config.vm.network :forwarded_port, guest: 80, host: 8080
      config.vm.network :forwarded_port, guest: 443, host: 8443
      config.vm.synced_folder "../../qatest", "/qatest"
      config.vm.synced_folder "../../package/debian/deb", "/packages"
  end

  # Build for Jessie / OS Perl
  config.vm.define "build-jessie" do |build|
      config.vm.box = "debian/jessie64"
      config.vm.hostname = "oxi-build-jessie"
      config.vm.provision :shell, :path => "provision-build.sh"
      config.vm.synced_folder "../..", "/code-repo"
  end

  # Build for Jessie / myperl 
  config.vm.define "build-myperl" do |buildmyperl|
      buildmyperl.vm.hostname = "oxi-build-myperl"
      buildmyperl.vm.box = "debian/jessie64"
      buildmyperl.vm.provision :shell, :path => "myperl/provision-build.sh"
      buildmyperl.vm.synced_folder "../..", "/code-repo"
      buildmyperl.vm.synced_folder "../../../myperl", "/myperl-repo"
      if @localcfg["mirror"]
          buildmyperl.vm.synced_folder @localcfg["mirror"], "/mirrors"
      end
      buildmyperl.vm.network "private_network", type: "dhcp"
  end

  # Test for Jessie / myperl
  config.vm.define "test-myperl" do |testmyperl|
      testmyperl.vm.box = "debian/jessie64"
      testmyperl.vm.hostname = "oxi-test-myperl"
      testmyperl.vm.synced_folder "../..", "/code-repo"
      testmyperl.vm.network "private_network", type: "dhcp"
      testmyperl.vm.provision :shell, :path => "myperl/provision-test.sh"
      testmyperl.vm.network :forwarded_port, guest: 80, host: 8080
      testmyperl.vm.network :forwarded_port, guest: 443, host: 8443
  end

  # Testing on Ubuntu Trusty 
  config.vm.define "test-trusty", primary:true do |test|
      config.vm.box = "ubuntu/trusty64"
      config.vm.hostname = "oxi-test-trusty"
      config.vm.provision :shell, :path => "provision-test.sh", :args => "ubuntu"
      config.vm.network :forwarded_port, guest: 80, host: 8080
      config.vm.network :forwarded_port, guest: 443, host: 8443
      config.vm.synced_folder "../../qatest", "/qatest"
      config.vm.synced_folder "../../package/debian/deb", "/packages"
  end

  # Build on Ubuntu Trusty
  config.vm.define "build-trusty" do |build|
      config.vm.box = "ubuntu/trusty64"
      config.vm.hostname = "oxi-build-trusty"
      config.vm.provision :shell, :path => "provision-build.sh"
      config.vm.synced_folder "../..", "/code-repo"
  end


  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
  #   vb.gui = true
  #
    # Use VBoxManage to customize the VM. For example to change memory:
  vb.customize ["modifyvm", :id, "--memory", "1024"]
  #vb.customize ["modifyvm", :id, "--memory", "512"]
  end
  #

  config.ssh.forward_agent = true
end
