Vagrant.configure("2") do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  # "contrib" release is required because the virtualbox clients are not
  # included in the base packages
  config.vm.box = "debian/contrib-buster64"

  # Default VM - testing
  config.vm.define "test", primary: true do |test|
    test.vm.hostname = "oxi-test"
    test.vm.provision :shell, :path => "provision-test.sh"
    test.vm.network :forwarded_port, guest: 80, host: 8080
    test.vm.network :forwarded_port, guest: 443, host: 8443
    test.vm.synced_folder "../../qatest", "/qatest"
    test.vm.synced_folder "../../package/debian/deb", "/packages"
  end

  config.vm.define "develop" do |develop|
    develop.vm.hostname = "oxi-dev"
    develop.vm.provision :shell, :path => "provision-develop.sh"
    develop.vm.network :forwarded_port, guest: 80, host: 8080
    develop.vm.network :forwarded_port, guest: 443, host: 8443
    develop.vm.synced_folder "../../", "/code-repo"
  end

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.ssh.forward_agent = true
end
