# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# To add local overrides, create the file Vagrantfile.local. Example:
#
#   config_values[:mirror] = ENV['HOME'] + '/Data/mirrors'

Vagrant.configure("2") do |config|

#    config_values = {}

    if File.file?('Vagrantfile.local')
        external = File.read 'Vagrantfile.local'
        eval external
    end

  # Every Vagrant virtual environment requires a box to build off of.
  #config.vm.box = "deb-wheezy-amd64"
  config.vm.box = "sintec/wheezy64"

#  if config_values[:mirrors]
#    config.vm.synced_folder config_values[:mirrors], "/mirrors"
#  end

 # config.vm.define "build", primary: true do |build|
 #     config.vm.hostname = "build"
 #     config.vm.provision :shell, :path => "provision-build.sh"
 #     config.vm.synced_folder "../..", "/code-repo"
 # end

  config.vm.define "test", primary:true do |test|
      config.vm.hostname = "test-wheezy"
      config.vm.provision :shell, :path => "provision-test.sh"
      config.vm.network :forwarded_port, guest: 80, host: 8080
      config.vm.network :forwarded_port, guest: 443, host: 8443
      config.vm.synced_folder "../../qatest", "/qatest"
  end

  config.vm.define "build-wheezy" do |build|
      config.vm.hostname = "oxi-build-wheezy"
      config.vm.provision :shell, :path => "provision-build.sh"
      config.vm.synced_folder "../..", "/code-repo"
  end
  
  config.vm.define "test-trusty", primary:true do |test|
      config.vm.box = "williamwu/ubuntu-14.04-server-x64-eng"
      config.vm.hostname = "test-trusty"
      config.vm.provision :shell, :path => "provision-test.sh", :args => "ubuntu"
      config.vm.network :forwarded_port, guest: 80, host: 8080
      config.vm.network :forwarded_port, guest: 443, host: 8443
      config.vm.synced_folder "../../qatest", "/qatest"
  end

  config.vm.define "build-trusty" do |build|
      config.vm.box = "williamwu/ubuntu-14.04-server-x64-eng"
      config.vm.hostname = "oxi-build-trusty"
      config.vm.provision :shell, :path => "provision-build.sh"
      config.vm.synced_folder "../..", "/code-repo"
  end


  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
  #   vb.gui = true
  #
    # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  #vb.customize ["modifyvm", :id, "--memory", "512"]
  end
  #

  config.ssh.forward_agent = true
end
