# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# To add local overrides, create the file Vagrantfile.local. Example:
#
#   config_values[:mirror] = ENV['HOME'] + '/Data/mirrors'

Vagrant.configure("2") do |config|

#    config_values = {}

    if File.file?('Vagrantfile.local')
        external = File.read 'Vagrantfile.local'
        eval external
    end

  # Every Vagrant virtual environment requires a box to build off of.
  #config.vm.box = "deb-wheezy-amd64"
  config.vm.box = "opensuse-12-3-x64"

  # Details about the box: https://github.com/mapleoin/openSUSE-vagrant-box
  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url =
      "http://bit.ly/openSUSE-12-3-virtualbox-box"
  
#  if config_values[:mirrors]
#    config.vm.synced_folder config_values[:mirrors], "/mirrors"
#  end

  config.vm.define "build", primary: true do |build|
      config.vm.hostname = "build"
      config.vm.provision :shell, :path => "provision-build.sh"
      config.vm.synced_folder "../..", "/code-repo"
  end

  config.vm.define "test" do |test|
      config.vm.hostname = "test"
      config.vm.network :forwarded_port, guest: 443, host: 8443
  end

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
  #   vb.gui = true
  #
    # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  #vb.customize ["modifyvm", :id, "--memory", "512"]
  end
  #

  config.ssh.forward_agent = true
end
