#!/bin/sh
set -e

if [ ! -z "$1" ] && [ -d "$1" ]; then 
   target=$1;
else
   target=/var/www/htdocs
fi

## if you activate this then every run via cronjob creates an email
## echo "Installing to target $target";

old=`pwd`
cd $target

## Legacy problem: cvs folder is named doc, should be docs - so we make a link

if [ ! -L doc ] && [ ! -d doc ]; then
  ln -s docs doc 
fi;

## update CVS

#svn checkout svn://svn.berlios.de/openxpki/www.openxpki.org/trunk/htdocs $target 2>/dev/null >/dev/null
if [ $DEBUG ]; then
    CMD="svn checkout https://svn.sourceforge.net/svnroot/openxpki/www.openxpki.org/trunk/htdocs $target"
    echo Command: $CMD
    `$CMD`
else
    svn checkout https://svn.sourceforge.net/svnroot/openxpki/www.openxpki.org/trunk/htdocs $target 2>/dev/null >/dev/null
fi
# new syntax at sf:
cvs -z3 -d:pserver:anonymous@openca.cvs.sourceforge.net:/cvsroot/openca co -P doc >/dev/null 2>&1

## copy stuff to htdocs area

## create symlinks if necessary
# images for One Page HTML Guide
cd docs/guide/
rm -rf images
ln -s src/images

# legacy link
rm -rf html_chunked
ln -s html html_chunked

# provide .css for /docs/guide/openca-guide.html
# NB: link does not work here!
cp html/default.css .

# images for chunked html
cd html
rm -rf images
ln -s ../src/images

## Update nightly snapshot
cd $target
${old}/fetch.sh                                                                                   

cd $old

#echo "update succeeded"
