package OpenXPKI::Crypt::Profile::DTO::CustomOid;
use OpenXPKI -class;

=head1 NAME

OpenXPKI::Crypt::Profile::DTO::CustomOid - DTO for a custom OID extension

=head1 DESCRIPTION

Represents one entry from the C<oid> section of a certificate profile.
Custom OIDs are identified by their dotted-decimal OID string.

=head1 ATTRIBUTES

=head2 oid (Str, required)

The OID in dotted-decimal notation.

=cut

has oid => (
    is       => 'ro',
    isa      => 'OID',
    required => 1,
);

=head2 critical (Bool, required)

Whether the extension is marked critical.

=cut

has critical => (
    is       => 'ro',
    isa      => 'Bool',
    required => 1,
);

=head2 value (ArrayRef[GeneralNameNoBreak], required)

The extension value lines. May be passed as a plain string to the constructor,
in which case it is split on C<\r?\n>. Each element may include C<format:>
and C<encoding:> prefixes. For SEQUENCE extensions the lines are the raw
section content.

=cut

has value => (
    is       => 'ro',
    isa      => 'ArrayRef[GeneralNameNoBreak]',
    required => 1,
);

around BUILDARGS => sub {
    my ($orig, $class, %args) = @_;
    if (exists $args{value} && !ref $args{value}) {
        $args{value} = [ split /\r?\n/, $args{value} ];
        $args{encoding} = 'SEQUENCE' if (scalar @{$args{value}} > 1);
    }
    return $class->$orig(%args);
};

=head2 format (Str)

Optional format prefix (e.g. C<DER>, C<HEX>).

=cut

has format => (
    is  => 'ro',
    isa => 'Str',
    lazy => 1,
    default => '',
);

=head2 encoding (Str)

Optional ASN.1 encoding type (e.g. C<UTF8String>, C<IA5String>). Set to
C<SEQUENCE> when the value is an ASN.1 SEQUENCE.

=cut

has encoding => (
    is  => 'ro',
    isa => 'Str',
    default => '',
);

=head2 section_name (Str)

Autogenerated from the OID.

=cut

has section_name => (
    is  => 'ro',
    isa => 'Str',
    lazy => '',
    reader => 'get_section_name',
    default => sub {
        my $oid = shift->oid;
        $oid =~ s/\./_/g;
        return 'oid_section_' . $oid;
    },
);


=head2 is_sequence (Bool, default 0)

True when the extension value is an ASN.1 SEQUENCE (C<encoding eq 'SEQUENCE'>).

=cut

sub is_sequence {
    return shift->encoding eq 'SEQUENCE';
}


=head2 get_config_line (Str)

Returns the primary configuration line to define the oid.
For sequences this only prints out the reference to the section header, add
the actual content by calling get_section_name / get_section_lines.

=cut

sub get_config_line {

    my $self = shift;
    my $val = '';

    $val = 'critical,' if ($self->critical);

    if ($self->is_sequence) {
        $val = 'ASN1:SEQUENCE:' . $self->get_section_name;
    } else {
        $val .= $self->format . ':' if $self->format;
        $val .= $self->encoding . ':' if $self->encoding;
        $val .= $self->value->[0];
    }
    return sprintf('%s=%s', $self->oid, $val)

}

=head2 get_section_lines (ArrayRef[GeneralNameNoBreak])

Returns the value of the sequence as arrayref B<excluding> the section header.

=cut

sub get_section_lines {

    my $self = shift;
    return [] unless($self->is_sequence);
    return $self->value;

}

__PACKAGE__->meta->make_immutable;

1;
