# -*- mode: ruby -*-
# vi: set ft=ruby :
#
#
# It is assumed that the configuration repository is checked out
# below config/ (relative to project root).
#
def virtualbox_version()
    vboxmanage = Vagrant::Util::Which.which("VBoxManage") || Vagrant::Util::Which.which("VBoxManage.exe")
    if vboxmanage != nil
        s = Vagrant::Util::Subprocess.execute(vboxmanage, '--version')
        s = s.stdout.strip!
        s = s.split('_').first
        return s
    else
        return nil
    end
end

Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-buster64"

  # Do not try to update VirtualBox Guest Additions (which fails anyway).
  # Instead we do that manually in assets/provision-basic.sh
  config.vbguest.auto_update = false

  # Default VM - testing on debian jessie
  config.vm.define "develop", primary:true do |dev|
      dev.vm.hostname = "oxi-dev-alldb"
      dev.vm.synced_folder "../..", "/code-repo"

      # Install Docker runtime but don't do anything through Vagrant
      dev.vm.provision "docker" do |d|
      end

      # prevent Vagrant error "stdin: is not a tty"
      dev.vm.provision :shell, :inline => "sed -ri 's/^(mesg.*)/# \\1/' /root/.profile"

      # Basic setup
      dev.vm.provision :shell, :inline => "mkdir -p /run-env"
      dev.vm.provision :shell, :inline => "chmod 0777 /run-env"
      dev.vm.provision :shell, :path => "assets/provision-basic.sh", :args => virtualbox_version()

      # Install databases (partly as Docker images)
      #dev.vm.provision :shell, :path => "assets/oracle/provision.sh"
      dev.vm.provision :shell, :path => "assets/mysql/provision.sh"
      dev.vm.provision :shell, :path => "assets/sqlite/provision.sh"

      # Install OpenXPKI
      dev.vm.provision :shell, :path => "assets/provision-openxpki.sh"

      # Cleanup
      dev.vm.provision :shell, :path => "assets/provision-cleanup.sh"

      # TCP ports - OpenXPKI
      dev.vm.network :forwarded_port, guest: 80,   host: 8080, host_ip: "0.0.0.0"
      dev.vm.network :forwarded_port, guest: 443,  host: 8443, host_ip: "0.0.0.0"

      # TCP ports - Oracle WebUI (http://127.0.0.1:1080/apex)
      dev.vm.network :forwarded_port, guest: 1080, host: 1080, host_ip: "0.0.0.0"
  end

  config.vm.provider :virtualbox do |vb|
      # increase memory (Virtualbox)
      vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.ssh.forward_agent = true
end
