# -*- mode: ruby -*-
# vi: set ft=ruby :
#
#
# It is assumed that the configuration repository is checked out
# below config/ (relative to project root).
#
def virtualbox_version()
    vboxmanage = Vagrant::Util::Which.which("VBoxManage") || Vagrant::Util::Which.which("VBoxManage.exe")
    if vboxmanage != nil
        s = Vagrant::Util::Subprocess.execute(vboxmanage, '--version')
        s = s.stdout.strip!
        s = s.split('_').first
        return s
    else
        return nil
    end
end

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # Do not try to update VirtualBox Guest Additions (which fails anyway).
  # Instead we do that manually in assets/provision-basic.sh
  if defined? (config.vbguest)
      config.vbguest.auto_update = false
  end

  # Default VM - testing on debian jessie
  config.vm.define "develop", primary:true do |dev|
      dev.vm.hostname = "oxi-dev-alldb"


      dev.vm.synced_folder ".", "/vagrant", type: "sshfs"
      dev.vm.synced_folder "../..", "/code-repo", type: "sshfs"

      # prevent Vagrant error "stdin: is not a tty"
      dev.vm.provision "Edit /root/.profile", :type => "shell", :inline => "sed -ri 's/^(mesg.*)/# \\1/' /root/.profile"

      dev.vm.provision "Create /run-env", :type => "shell", :inline => "mkdir -p /run-env && chmod 0777 /run-env"

      dev.vm.provision "Provisioning", :type => "shell", :path => "provision.sh", :args => [ virtualbox_version() ]

      # TCP ports - OpenXPKI
      dev.vm.network :forwarded_port, guest: 80,   host: 9080, host_ip: "0.0.0.0"
      dev.vm.network :forwarded_port, guest: 443,  host: 9443, host_ip: "0.0.0.0"

      # TCP ports - Oracle WebUI (http://127.0.0.1:1080/apex)
      dev.vm.network :forwarded_port, guest: 1080, host: 9081, host_ip: "0.0.0.0"

      # Prometheus
      dev.vm.network :forwarded_port, guest: 9090, host: 9082, host_ip: "0.0.0.0"
  end

  config.vm.provider :virtualbox do |vb|
      # increase memory (Virtualbox)
      vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.ssh.forward_agent = true
end
