# trunk/package/debian/perl-client-api

TOPDIR=../../../..
PERLNAME=OpenXPKI-Client
SRCBASE=$(TOPDIR)/trunk/clients/perl/$(PERLNAME)
PACKAGE=libopenxpki-client-perl
PKGDIR=../deb/client_api

# Makefile.inc contains common settings for all packages (checked in)
include ../Makefile.inc
# Makefile.local may be used locally to override settings (not checked in)
-include ../Makefile.local

