#!/usr/bin/env perl
use Mojolicious::Lite;

use lib ('lib', '../../../qatest/lib');

use MockSCEPServer;

my $config = {
    basedir => $ENV{MOCK_SCEP_BASEDIR} || die "MOCK_SCEP_BASEDIR not set",
    verbose => $ENV{MOCK_SCEP_VERBOSE} || 0,
};

my $scepd = MockSCEPServer->new( config => $config );

#helper scepd => sub { state $scepd = MockSCEPServer->new( config => $config ) };

get '/scep' => sub {
    my $self = shift;
    #$self->scepd->handle($self);
    $scepd->handle($self);
};

app->start;
