# trunk/package/debian/mason-html-client

TOPDIR=../../../..
PERLNAME=OpenXPKI-Client-HTML-Mason
SRCBASE=$(TOPDIR)/trunk/clients/perl/$(PERLNAME)
PACKAGE=libopenxpki-client-html-mason-perl
PKGDIR=../deb/client

# Makefile.inc contains common settings for all packages (checked in)
include ../Makefile.inc
# Makefile.local may be used locally to override settings (not checked in)
-include ../Makefile.local

