#!/bin/bash

#
# This script is used in the Vagrant Box "develop"
#

## <info> Configure environment and install OpenXPKI from host sources
test $(whoami) != "root" && echo "Please run this as root: sudo $0" && exit 1
set -o pipefail

if [[
    -z $OXI_SOURCE_DIR ||
    -z $OXI_CORE_DIR ||
    -z $OXI_TEST_SAMPLECONFIG_DIR ||
    -z $OXI_TEST_DB_MYSQL_DBHOST ||
    -z $OXI_TEST_DB_MYSQL_DBPORT ||
    -z $OXI_TEST_DB_MYSQL_NAME ||
    -z $OXI_TEST_DB_MYSQL_USER ||
    -z $OXI_TEST_DB_MYSQL_PASSWORD
]]; then
    cat <<EOF
This script needs the following environment variables set:
    OXI_SOURCE_DIR              # OpenXPKI repository contents, e.g. /code-repo
    OXI_EE_SOURCE_DIR           # optional: EE source code
    OXI_CORE_DIR                # target, e.g. /opt/openxpki/core
    OXI_TEST_SAMPLECONFIG_DIR   # e.g. /code-repo/config
    OXI_TEST_DB_MYSQL_DBHOST
    OXI_TEST_DB_MYSQL_DBPORT
    OXI_TEST_DB_MYSQL_NAME
    OXI_TEST_DB_MYSQL_USER
    OXI_TEST_DB_MYSQL_PASSWORD
EOF
    exit 1
fi

#
# Exit handler
#
LOG=$(mktemp)
function _exit () {
    if [ $1 -ne 0 -a $1 -ne 333 ]; then
        echo "================================================================================"
        echo "$0: ERROR - last command exited with code $1, output:"
        echo "================================================================================"
        cat $LOG
    fi
    rm -f $LOG
    exit $1
}

[[ "${@#--help}" != "$@" ]] && cat <<__HELP && exit 1
SYNOPSIS
    $(basename "$0") [OPTIONS]

DESCRIPTION
    $(cat "$0" | grep "[[:blank:]]#*[[:blank:]]*<info>" | cut -d ">" -f2 | sed s/'^[[:blank:]]*'//)

OPTIONS
    --no-restart
        Skip restarting OpenXPKI and Apache/nginx.

    --no-i18n
        Skip updating internationalization files.

    --no-compile
        Skip compiling XS code parts.

    --no-ee
        Skip enterprise code.

    --fast
        Shortcut for "--no-i18n --no-compile --no-dbconfig".

    --full
        Overwrite /etc/openxpki with modified sample config.
        (Re-)create database and import certificates.

    --tenant
        Activate Tenant support for user "raop".

    --apache
        Switch to apache2 (disable nginx)

    --nginx
        Switch to nginx (disable apache2)
__HELP

trap '_exit $?' EXIT
set -e

#
# Command line options
#
IS_RESTART=1
IS_FULLCONFIG=0
TENANT_SUPPORT=0
IS_APACHE=0
FORCE_APACHE=0
FORCE_NGINX=0
oxi_install_params=()

# Bash string manipulation: use # to strip text off $@ and see if string still equals original $@
[[ "${@#--no-restart}" != "$@" || "${@#--norestart}" != "$@" ]] && IS_RESTART=0
[[ "${@#--fast}" != "$@" ]]       && oxi_install_params+=(--fast)
[[ "${@#--full}" != "$@" ]]       && IS_FULLCONFIG=1
[[ "${@#--no-i18n}" != "$@" ]]    && oxi_install_params+=(--no-i18n)
[[ "${@#--no-compile}" != "$@" ]] && oxi_install_params+=(--no-compile)
[[ "${@#--no-ee}" != "$@" ]]      && oxi_install_params+=(--no-ee)
[[ "${@#--tenant}" != "$@" ]]     && TENANT_SUPPORT=1
[[ "${@#--apache}" != "$@" ]]     && FORCE_APACHE=1
[[ "${@#--nginx}" != "$@" ]]      && FORCE_NGINX=1

if [[ $FORCE_NGINX == 1 ]]; then
    echo -e "Switching to nginx\n"
    systemctl disable apache2   >>$LOG 2>&1
    systemctl stop apache2      >>$LOG 2>&1
    systemctl enable nginx      >>$LOG 2>&1
elif [[ $FORCE_APACHE == 1 ]]; then
    echo -e "Switching to Apache2\n"
    systemctl disable nginx     >>$LOG 2>&1
    systemctl stop nginx        >>$LOG 2>&1
    systemctl enable apache2    >>$LOG 2>&1
fi
if [[ $(systemctl is-enabled apache2) == "enabled" ]]; then IS_APACHE=1; fi

IS_LEGACY_FCGI=0
if [[ $IS_APACHE == 1 ]]; then
    set +e
    IS_LEGACY_FCGI=$(grep -c '^\s*Define NoMojolicious' $OXI_TEST_SAMPLECONFIG_DIR/contrib/apache2-openxpki-site.conf)
    set -e
fi

echo "[$([[ $IS_FULLCONFIG == 1 ]]  && echo "X" || echo " ")] Recreate DB and certs, wipe config"
echo "[$([[ $IS_RESTART == 1 ]]     && echo "X" || echo " ")] Restart OpenXPKI & webserver"
echo -n "    Webserver: "
if [[ $IS_APACHE == 1 ]]; then
    echo -n "Apache"
    [[ $IS_LEGACY_FCGI == 1 ]] && echo " (with legacy FCGI client)" || echo " (with Mojolicious client)"
else
    echo "nginx"
fi
echo

# stop OpenXPKI early to prevent crashes due to DB access problems etc.
if [[ $IS_RESTART -eq 1 ]]; then
    set +e
    # service unit might not yet exist if this is a freshly installed system
    if systemctl list-unit-files openxpkid.service >/dev/null; then
        systemctl stop openxpkid.service
    fi
    if systemctl list-unit-files openxpki-clientd.service >/dev/null; then
        systemctl stop openxpki-clientd.service
    fi
    set -e
fi

#
# Configuration (copy and modify)
#

# fully overwrite existing config
if [[ $IS_FULLCONFIG -eq 1 ]]; then
    echo "Wipe any existing config and keys in /etc/openxpki"
    rm -rf /etc/openxpki

# keep keys and additional files
else
    echo "Update OpenXPKI config in /etc/openxpki"

    # remove workflow/def
    echo "- remove existing workflows"
    for realm_dir in /etc/openxpki/config.d/realm/*; do
        rm -rf "$realm_dir/workflow/def"
    done
fi

# copy config/ to /etc/openxpki
echo "- copy config"
pushd $OXI_TEST_SAMPLECONFIG_DIR > /dev/null
    DESTDIR= make install >>$LOG 2>&1
popd > /dev/null

mkdir -p /etc/openxpki/local/keys

chmod 750              /etc/openxpki/config.d
chown -R root:openxpki /etc/openxpki/config.d

mv /etc/openxpki/local/keys /tmp/openxpki-keys
rsync -a --delete $OXI_TEST_SAMPLECONFIG_DIR/contrib/local/* /etc/openxpki/local/ >>$LOG 2>&1
chmod 750              /etc/openxpki/local
chown -R root:openxpki /etc/openxpki/local
mv /tmp/openxpki-keys /etc/openxpki/local/keys

# set en_US as default language to get correct I18N translations (e.g. in rpc.fcgi)
sed -ri 's/^(\s*default_language:).*/\1 en_US/' /etc/openxpki/config.d/system/server.yaml

# set plain datavault password "root"
sed -zri 's/(secret:\s+default:\s+.*?)value@?:[^\n]+/\1value: root/' /etc/openxpki/config.d/system/crypto.yaml

# Specify hostname to force MySQL connection via TCP, not socket
webui_conf=/etc/openxpki/client.d/service/webui/default.yaml
if [ -e $webui_conf ]; then
    echo "- set WebUI session driver to database"
    sed -ri 's/^(\s*)(#\s*)?(driver)\s*:.*/\1\3: driver:openxpki/'                                $webui_conf
    sed -ri 's/^(\s*)(#\s*)?(DataSource)\s*:.*/\1\3: dbi:MariaDB:dbname=openxpki;host=127.0.0.1/' $webui_conf
    sed -ri 's/^(\s*)(#\s*)?(User)@?\s*:.*/\1\3: openxpki_session/'                               $webui_conf
    sed -ri 's/^(\s*)(#\s*)?(Password)@?\s*:.*/\1\3: mysecret/'                                   $webui_conf
    sed -ri 's/^(\s*)(#\s*)?(EncryptKey)@?\s*:.*/\1\3: mysecret/'                                 $webui_conf
fi
legacy_webui_conf=/etc/openxpki/webui/default.conf
if [ -e $legacy_webui_conf ]; then
    echo "- set legacy WebUI session driver to database"
    sed -ri 's/^(#\s*)?(driver\s*=).*/\2 driver:openxpki/'                                $legacy_webui_conf
    sed -ri 's/^(#\s*)?(DataSource\s*=).*/\2 dbi:MariaDB:dbname=openxpki;host=127.0.0.1/' $legacy_webui_conf
    sed -ri 's/^(#\s*)?(User\s*=).*/\2 openxpki_session/'                                 $legacy_webui_conf
    sed -ri 's/^(#\s*)?(Password\s*=).*/\2 mysecret/'                                     $legacy_webui_conf
fi

set +e
test_auth_exists=$(grep -c "Testing:" /etc/openxpki/config.d/realm/democa/auth/stack.yaml)
set -e

if [ $test_auth_exists -eq 0 ]; then
    echo "- add authentication stack 'Testing'"
    # add test auth stack (e.g. user: raop / password: openxpki)
    sed -zri 's/^/Testing:\n    handler: TestAccounts\n    type: passwd\n\n/' /etc/openxpki/config.d/realm/democa/auth/stack.yaml
fi

# add "tenant: { type: Base }" to "RA Operator"
if [ $TENANT_SUPPORT -eq 1 ]; then
    echo "- add tenant config"
    sed -zri 's/(RA Operator[^\n]+\n([\t ]+[^\n]+\n)+)/\1    tenant:\n        type: Base\n/' /etc/openxpki/config.d/realm/democa/auth/roles.yaml
fi

# remove probably existing TestAccounts
sed -zri 's/(TestAccounts:\n([\t ]+[^\n]+\n|\n)+)//' /etc/openxpki/config.d/realm.tpl/auth/handler.yaml

# add our TestAccounts
echo "- add OpenXPKI test accounts"
cat <<__HANDLER >> /etc/openxpki/config.d/realm/democa/auth/handler.yaml

TestAccounts:
    type: Password
    label: Test Accounts
    user:
        caop:
            digest: "{ssha}JQ2BAoHQZQgecmNjGF143k4U2st6bE5B"
            role: CA Operator
            realname: Christina Op
            email: ca@example.org
        raop:
            digest: "{ssha}JQ2BAoHQZQgecmNjGF143k4U2st6bE5B"
            role: RA Operator
            realname: Richard Alfred Op
            email: ra@example.org
            tenant:
                - Alice Group
                - Bob the Builder
        user:
            digest: "{ssha}JQ2BAoHQZQgecmNjGF143k4U2st6bE5B"
            role: User
            realname: User No. 1
            email: user@example.org
__HANDLER

# set /var/tmp instead of /tmp (where only root has write access)
sed -ri 's/(LOCATION:)\s*\/tmp.*/\1 \/var\/tmp/g' /etc/openxpki/config.d/realm/democa/publishing.yaml

# database setup
echo "- configure MariaDB as database"
cat <<__DB > /etc/openxpki/config.d/system/database.yaml
main:
    debug: 0
    type: MariaDB2
    host: $OXI_TEST_DB_MYSQL_DBHOST
    port: $OXI_TEST_DB_MYSQL_DBPORT
    name: $OXI_TEST_DB_MYSQL_NAME
    user: $OXI_TEST_DB_MYSQL_USER
    passwd: $OXI_TEST_DB_MYSQL_PASSWORD
__DB

if [[ $IS_LEGACY_FCGI == 0 ]]; then
    echo "- client config: allow webserver user to connect to client socket"
    perl -pe 's{^(socket_group)\s*:.*}{$1: www-data}g;' -i /etc/openxpki/client.d/system/server.yaml
else
    echo "- legacy FCGI client config: allow FCGI user to connect to server socket"
    perl -pe 's{^(socket_group)\s*:.*}{$1: www-data}g;' -i /etc/openxpki/config.d/system/server.yaml
fi

echo "- inject HSM terminal simulation config"
cat <<__EOF > /etc/openxpki/config.d/system/terminal.yaml
ncipher:
    internal: 1
    command: /bin/bash -c $OXI_SOURCE_DIR/tools/testenv/hsm-sim.sh
    pid_file: /run/openxpki-terminal/terminal-intproc.pid
    socket_file: /run/openxpki-terminal/terminal-intproc.sock
__EOF

cat <<__EOF >> "/etc/openxpki/config.d/realm/democa/uicontrol/RA Operator/main.yaml"
- key:   ncipher
  label: nCipher Sim
  icon: glyphicon-lock
__EOF

#
# Compile and install OpenXPKI
#
echo ""
echo "Install OpenXPKI"
$(dirname $0)/oxi-install "${oxi_install_params[@]}" | sed -u 's/^/    /mg'

# Read VERSION generated by oxi-install
ver=$(perl -I $OXI_CORE_DIR/server -e 'use OpenXPKI::VERSION; print join ".", (split /\./, $OpenXPKI::VERSION::VERSION)[0,1]')

# Modify version in config dependency
echo -e "\nModify version check for core: $ver"
perl -pe "s{^(\s+core):.*}{\$1: $ver}g;" -i /etc/openxpki/config.d/system/version.yaml

# configure web server
if [[ $IS_APACHE == 1 ]]; then
    echo -e "Configure Apache web server"
    cat $OXI_TEST_SAMPLECONFIG_DIR/contrib/apache2-openxpki-site.conf \
    | perl -pe 's{^(\s*RewriteRule \^\.\*\$ https://)}{#$1}'\
    > /etc/apache2/sites-available/openxpki.conf
    /usr/sbin/a2ensite openxpki > /dev/null
    /usr/sbin/a2enmod ssl cgid fcgid headers rewrite proxy proxy_http macro > /dev/null
else
    echo -e "Configure nginx web server"
    cp $OXI_TEST_SAMPLECONFIG_DIR/contrib/nginx-openxpki-site /etc/nginx/sites-available/openxpki
    nginx -t 2>&1 | sed 's/^/ > /'
fi

# Enable "Keyword Tests"
kwt_bin=$(command -v openxpkikwt)
if [[ -e $OXI_TEST_SAMPLECONFIG_DIR/contrib/test/test.yaml && -n $kwt_bin ]]; then
    echo "Enable Keyword Test config overlay"
    export OPENXPKI_BACKDOOR_ENABLED=1
    pushd $OXI_TEST_SAMPLECONFIG_DIR/contrib/test >/dev/null
    rm -f test.yaml && ln -s test.yaml.tpl test.yaml
    openxpkikwt prepare | sed 's/^/ > /'
    popd >/dev/null
fi

# create SSL keys and certificates and import them into OpenXPKI
if [[ $IS_FULLCONFIG -eq 1 ]]; then
    echo ""
    $(dirname $0)/oxi-initdb
fi

if [[ $IS_RESTART -eq 1 ]]; then
    echo ""

    # oxi-initdb (above) already restarts OpenXPKI
    if [[ $IS_FULLCONFIG -eq 1 ]]; then
        echo "Restart OpenXPKI server"
        systemctl restart openxpkid.service
        set +e
        sec=0; error=1; sock=$(perl -e 'use OpenXPKI::Defaults; print $OpenXPKI::Defaults::SERVER_SOCKET')
        while [ $error -ne 0 -a $sec -lt 20 ]; do
            test -e $sock; error=$?; sec=$[$sec+1]
            sleep 1
        done
        set -e
        if [ $error -ne 0 ]; then
            echo -e "\nERROR: Could not start server. Please see logs in /var/log/openxpki"
            exit 333
        fi
    fi

    if [[ $IS_LEGACY_FCGI == 0 ]]; then
        echo "Restart OpenXPKI client (Mojolicious)"
        systemctl restart openxpki-clientd.service
        if ! systemctl status openxpki-clientd.service > /dev/null; then
            echo -e "\nERROR: Could not start client. Please see logs in /var/log/openxpki-ui"
            exit 333
        fi
    else
        echo "Legacy FCGI: disable OpenXPKI Mojolicious client"
        systemctl disable openxpki-clientd.service
    fi

    if [[ $IS_APACHE == 1 ]]; then
        echo "Restart Apache"
        systemctl restart apache2
    else
        echo "Restart nginx"
        systemctl restart nginx
    fi
fi

echo -e "\nDone."
