%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Connector
Version:        0.11
Release:        1%{?dist}
Summary:        Generic connection to data sets
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://github.com/mrscotty/connector
Source0:        file:///home/scotty/git/connector/Connector-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
# Moose -> Moose
BuildRequires:  perl(Moose)
# Test::More -> Test-More
BuildRequires:  perl(Test::More)
Requires:       perl(Moose)

%description
The Connector is generic connection to a data set, typically configuration
data in a hierarchical structure. Each connector object accepts the get(KEY)
method, which, when given a key, returns the associated value from the
connector's data source.

%prep
%setup -q -n Connector-%{version}

%build
%{__perl} Makefile.PL INSTALL_BASE=/usr/local INSTALLDIRS=vendor
make

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

perldoc -t perlgpl > COPYING
perldoc -t perlartistic > Artistic

%check || :
echo "tests disabled"

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc README.mkd COPYING Artistic
/usr/local/*

%changelog
* Mon Apr 23 2012 <Scott T. Hardin> 0.5-1
- Specfile autogenerated by cpanspec 1.78.
