%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Crypt-ECDH
Version:        0.10
Release:        1%{?dist}
Summary:        Inline C elliptic curve Diffi-Hellman implementation using the openSSL lib
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            gitolite@mnemonic:users/litwinczuk/ecdh
Source0:        Crypt-ECDH-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)


%description
Generate elliptic curve PEM encoded keypairs and an elliptic curve Diffi-Hellman key

%prep
%setup -q -n Crypt-ECDH-%{version}

rm -f pm_to_blib

%build
%{__perl} Makefile.PL INSTALL_BASE=/usr/local INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

perldoc -t perlgpl > COPYING
perldoc -t perlartistic > Artistic

%check || :
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc build.mkd Changes commands README COPYING Artistic
/usr/local/*

%changelog
* Fri Apr 27 2012 <Scott T. Hardin> 0.6-1
- Specfile autogenerated by cpanspec 1.78.
