package OpenXPKI::Crypto::Backend::OpenSSL::Config;
use OpenXPKI;

use OpenXPKI::Server::Context qw( CTX );

use OpenXPKI::DN;
use OpenXPKI::DateTime;
use OpenXPKI::FileUtils;

sub new
{
    my $that = shift;
    my $class = ref($that) || $that;

    my $self = shift || {};
    bless $self, $class;

    return $self;
}

############################
##     Public setters     ##
############################

sub set_engine
{
    my $self = shift;
    $self->{ENGINE} = shift;
    return $self;
}

sub set_profile
{
    my $self = shift;
    $self->{PROFILE} = shift;
    return $self;
}

sub set_crl_items {

    my $self = shift;
    my $list = shift;
    $self->{INDEX_TXT} = "";

    my @index;
    foreach my $item (@$list) {

        ##! 64: 'CRL item ' . Dumper $item
        my $rawserial = shift @{$item};
        # Constructor detects leading 0x as hex, unpack creates a paired hex output
        my $serial = unpack('H*', Math::BigInt->new( $rawserial )->to_bytes );

        my $timestamp = '700101000000Z';
        my $reason_code = 'unspecified';

        if (scalar @{$item}) {
            my $epoch = shift @{$item};
            $timestamp = OpenXPKI::DateTime::convert_date({
                DATE      => DateTime->from_epoch(epoch => $epoch),
                OUTFORMAT => 'openssltime',
            }) if ($epoch);

            if (scalar @{$item}) {
                $reason_code = shift @{$item};
                if ($reason_code !~ m{ \A (?: unspecified | keyCompromise | CACompromise | affiliationChanged | superseded | cessationOfOperation | certificateHold | removeFromCRL ) \z }xms) {
                    CTX('log')->application()->warn("Invalid reason code '" . $reason_code . "' specified");
                    $reason_code = 'unspecified';
                }

                if ($reason_code eq 'keyCompromise' && scalar @{$item} && $item->[0]) {
                    my $invalidity_time = shift @{$item};
                    eval {
                        my $invalidity_date = OpenXPKI::DateTime::convert_date({
                            DATE      => DateTime->from_epoch( epoch => $invalidity_time ),
                            OUTFORMAT => 'generalizedtime',
                        });
                        ##! 16: 'invalidity date is present: ' . $invalidity_date . ' / ' . $invalidity_time

                        # openssl needs a special reason code keyword to pickup
                        # the invalidity time parameter
                        $reason_code = 'keyTime,'.$invalidity_date;
                    };
                    if ($EVAL_ERROR) {
                        CTX('log')->application()->warn("Unparsable invalidity_date given: " . $invalidity_time);
                    }
                }
            }
        }

        my $revocation = "$timestamp,$reason_code";

        push @index, join("\t",('R', '700101000000Z', $revocation, $serial, 'unknown', '/DC=org/DC=openxpki/CN=Dummy'));

    }
    push @index,"";

    $self->{INDEX_TXT} = join("\n", @index);

    ##! 1: "end"
    return $self;
}

sub __get_fu {

    my $self = shift;
    $self->{FU} ||= OpenXPKI::FileUtils->new({ TMP => $self->{TMP} });
    return $self->{FU};
}

################################
##     Dump configuration     ##
################################

sub dump
{
    ##! 1: "start"
    my $self = shift;
    my $config = $self->build_config();

    # directory mode for ca operations
    if ($self->{CONFDIR}) {
        $self->{FILENAME}->{CONFIG} = $self->{CONFDIR}."/openssl.cnf";

        ##! 2: "write configuration file " . $self->{FILENAME}->{CONFIG}
        # writes a "non-temporary" file inside the temporary directory
        $self->__get_fu()->write_file ({
            FILENAME => $self->{FILENAME}->{CONFIG},
            CONTENT  => $config
        });

    # single file mode
    } else {

        $self->{FILENAME}->{CONFIG} = $self->__get_fu()->write_temp_file( $config );

    }
    return $self->{FILENAME}->{CONFIG};

}

sub build_config
{
    ##! 1: "start"
    my $self = shift;

    my @config = (
        '## OpenSSL configuration',
        '## dynamically generated by OpenXPKI::Crypto::Backend::OpenSSL::Config',
        '',
        'default_ca   = ca');

    if (my @engines = $self->__get_engine()) {
        push @config,
            'openssl_conf = openssl_init',
            '[ openssl_init ]',
            'engines = engine_section',
            @engines;
    }

    # We overwrite the DN by -subj so this is irrelevant but OpenSSL
    # requires a policy item to be set
    push @config, '[ dn_policy ]', 'domainComponent = optional';

    my $profile = $self->{PROFILE};

    if (!$profile || !blessed($profile)
        || $profile->isa('OpenXPKI::Crypt::Profile::CSR'))
    {
        # PKCS#10 creation (no profile or CSR profile)
        push @config, $self->__get_req_section();

    } elsif ($profile->isa('OpenXPKI::Crypt::Profile::Certificate')) {

        $self->__prepare_ca_files($profile);
        push @config, $self->__get_ca_section($profile);
        if (my @ext = $self->__get_cert_extensions('v3ca', $profile)) {
            push @config, @ext;
        } else {
            push @config, '[ v3ca ]';
        }

    } elsif ($profile->isa('OpenXPKI::Crypt::Profile::CRL')) {

        $self->__prepare_ca_files($profile);
        push @config, $self->__get_ca_section($profile);
        if (my @ext = $self->__get_shared_extensions('v3ca', $profile)) {
            push @config, @ext;
        } else {
            push @config, '[ v3ca ]';
        }

    } else {
        OpenXPKI::Exception->throw(
            message => 'Unknown profile class',
            params  => { class => ref $profile },
        );
    }

    ##! 16: \@config
    ##! 1: "end"

    return join("\n", @config);
}

sub __get_engine
{
    ##! 4: "start"
    my $self = shift;

    return unless($self->{ENGINE});

    my $engine_name = $self->{ENGINE}->get_engine();
    return unless($engine_name);

    # note - engine section is a multi-line string
    # so we get a mixed format here
    return ('[ engine_section ]',
        $engine_name . ' = engine_config',
        '',
        '[ engine_config ]',
        $self->{ENGINE}->get_engine_section(),
        '');
}

################################
##     Sanitization helpers   ##
################################

# Remove all control characters (including newlines) and escape double quotes.
# Prevents config injection via user-supplied string values.
sub _sanitize_value {
    my ($self, $str) = @_;
    return '' unless defined $str;
    $str =~ s/[\x00-\x1F\x7F]/ /g;
    $str =~ s/"/''/g;
    return $str;
}

# Like _sanitize_value but also percent-encodes , and ; which OpenSSL uses
# as field separators inside extension values.
sub _sanitize_uri {
    my ($self, $uri) = @_;
    $uri = $self->_sanitize_value($uri);
    $uri =~ s{,}{%2C}g;
    $uri =~ s{;}{%3B}g;
    return $uri;
}

# Returns true only for dotted-decimal OID notation.
sub _is_valid_oid {
    my ($self, $oid) = @_;
    return defined($oid) && $oid =~ /\A\d+(?:\.\d+)+\z/;
}

################################
##     CA file preparation    ##
################################

sub __prepare_ca_files {
    my ($self, $profile) = @_;

    $self->__get_fu();
    my $tmpdir = $self->{FU}->get_tmp_dirhandle()->dirname();
    $self->{CONFDIR} = $tmpdir;

    my $serial = $profile->get_serial();
    if (defined $serial) {
        $self->{FILENAME}->{SERIAL} = "$tmpdir/serial";
        $serial = Math::BigInt->new($serial);
        OpenXPKI::Exception->throw(
            message => "I18N_OPENXPKI_CRYPTO_OPENSSL_CONFIG_DUMP_WRONG_SERIAL",
        ) unless defined $serial;
        my $hex = unpack('H*', $serial->to_bytes);
        $self->{FU}->write_file({
            FILENAME => $self->{FILENAME}->{SERIAL},
            CONTENT  => $hex,
        });
        $self->{FILENAME}->{NEW_CERT} = "$tmpdir/$hex.pem";
    }

    # FIXME: The .attr file (index.txt.attr) is written unconditionally but
    # we assume it does not already exist - this may not be safe in all cases.
    # OpenSSL requires the file but does not create it automatically.
    $self->{FILENAME}->{DATABASE} = "$tmpdir/index.txt";
    $self->{FILENAME}->{ATTR}     = $self->{FILENAME}->{DATABASE} . ".attr";

    if (exists $self->{INDEX_TXT}) {
        $self->{FU}->write_file({
            FILENAME => $self->{FILENAME}->{DATABASE},
            CONTENT  => $self->{INDEX_TXT},
        });
    } else {
        $self->{FU}->write_file({
            FILENAME => $self->{FILENAME}->{DATABASE},
            CONTENT  => "",
        });
    }
    $self->{FU}->write_file({
        FILENAME => $self->{FILENAME}->{ATTR},
        CONTENT  => "unique_subject = no\n",
    });
}

################################
##     [ca] section builder   ##
################################

sub __get_ca_section {
    my ($self, $profile) = @_;

    OpenXPKI::Exception->throw(
        message => 'serial number file does not exist',
    ) unless exists $self->{FILENAME}->{SERIAL};

    my $digest = $profile->get_digest();
    OpenXPKI::Exception->throw(
        message => 'MD5 digest is broken and therefore not allowed',
    ) if $digest =~ /md5/;

    my @config = ('', '[ ca ]',
        'new_certs_dir   = ' . $self->{CONFDIR},
        'certificate     = ' . $self->{ENGINE}->get_certfile(),
        'private_key     = ' . $self->{ENGINE}->get_keyfile(),
        'crlnumber       = ' . $self->{FILENAME}->{SERIAL},
        'serial          = ' . $self->{FILENAME}->{SERIAL},
        'default_md      = ' . $digest,
        'database        = ' . $self->{FILENAME}->{DATABASE},
        'x509_extensions = v3ca',
        'crl_extensions  = v3ca',
        'preserve        = yes',
        'policy          = dn_policy',
        'name_opt        = RFC2253,-esc_msb',
        'utf8            = yes',
        'string_mask     = ' . $profile->get_string_mask(),
        '',
    );

    if ($profile->isa('OpenXPKI::Crypt::Profile::Certificate')) {

        if (my $notbefore = $profile->get_notbefore()) {
            my $startdate = OpenXPKI::DateTime::convert_date({
                OUTFORMAT => ($notbefore->year > 2049 ? 'generalizedtime' : 'openssltime'),
                DATE      => $notbefore,
            });
            push @config, 'default_startdate = ' . $startdate;
        }

        if (my $notafter = $profile->get_notafter()) {
            my $enddate = OpenXPKI::DateTime::convert_date({
                OUTFORMAT => ($notafter->year > 2049 ? 'generalizedtime' : 'openssltime'),
                DATE      => $notafter,
            });
            push @config, 'default_enddate = ' . $enddate;
        }

        my $copy_ext = $profile->get_copy_extensions();
        if ($copy_ext ne 'none') {
            push @config, 'copy_extensions = ' . $copy_ext;
        }

    } elsif ($profile->isa('OpenXPKI::Crypt::Profile::CRL')) {

        push @config,
            'default_crl_days  = ' . $profile->get_nextupdate_in_days(),
            'default_crl_hours = ' . $profile->get_nextupdate_in_hours();

    }

    return @config;
}

################################
##     Extension builders     ##
################################

# Extensions for certificate profiles (cert-specific + shared)
sub __get_cert_extensions {
    my ($self, $section_name, $profile) = @_;

    my @config   = ("[ $section_name ]");
    my @sections;

    # — BasicConstraints —
    if (my $dto = $profile->basic_constraints) {
        my $crit = $dto->critical ? 'critical,' : '';
        my @bc = ($dto->ca ? 'CA:true' : 'CA:false');
        push @bc, sprintf('pathlen:%01d', $dto->path_length)
            if defined $dto->path_length;
        push @config, "basicConstraints = $crit" . join(',', @bc);
    }

    # — KeyUsage —
    if (my $dto = $profile->key_usage) {
        my $crit  = $dto->critical ? 'critical,' : '';
        push @config, "keyUsage = $crit" . join(',', @{ $dto->bits }) if @{ $dto->bits };
    }

    # — ExtendedKeyUsage —
    if (my $dto = $profile->extended_key_usage) {
        my $crit = $dto->critical ? 'critical,' : '';
        push @config, "extendedKeyUsage = $crit" . join(',', @{ $dto->usages }) if @{ $dto->usages };
    }

    # — SubjectKeyIdentifier —
    if (my $dto = $profile->subject_key_identifier) {
        my $crit = $dto->critical ? 'critical,' : '';
        push @config, "subjectKeyIdentifier = ${crit}hash";
    }

    # — CRL Distribution Points —
    if (my $dto = $profile->crl_distribution_points) {
        my $crit = $dto->critical ? 'critical,' : '';
        push @config, "crlDistributionPoints = ${crit}\@cdp_section";
        push @sections, '', '[cdp_section]';
        my $i = 0;
        for my $uri (@{ $dto->uris }) {
            push @sections, "URI.$i=" . $self->_sanitize_uri($uri);
            $i++;
        }
        push @sections, '';
    }

    # — PolicyIdentifier —
    if (my $dto = $profile->policy_identifier) {
        my $crit = $dto->critical ? 'critical,' : '';
        my ($sn, $nn) = (0, 0);
        my (@policies, @psection, @notices);

        for my $policy (@{ $dto->policies }) {
            unless ($self->_is_valid_oid($policy->oid)) {
                CTX('log')->application()->warn(
                    "Skipping policy with invalid OID: " . ($policy->oid // ''));
                next;
            }
            if ($policy->cps || $policy->user_notice) {
                $sn++;
                push @policies, "\@policysection$sn";
                push @psection, "[ policysection$sn ]";
                push @psection, "policyIdentifier = " . $policy->oid;
                my $cc = 0;
                for my $cps (@{ $policy->cps // [] }) {
                    push @psection, 'CPS.' . (++$cc) . '="'
                        . $self->_sanitize_uri($cps) . '"';
                }
                for my $note (@{ $policy->user_notice // [] }) {
                    $nn++;
                    push @psection, "userNotice.$nn = \@notice$nn";
                    push @notices, "[ notice$nn ]",
                        # RFC recommends UTF8String here, but OpenSSL < 1.1 could
                        # not encode it that way; the UTF8 prefix was introduced
                        # with OpenSSL 1.1, so we emit a plain string.
                        'explicitText = "' . $self->_sanitize_value($note) . '"';
                }
            } else {
                push @policies, $policy->oid;
            }
        }

        if (@policies) {
            push @config, "certificatePolicies = $crit" . join(',', @policies), '';
            push @sections, '# Policies', @psection, '';
            push @sections, '# Notices', @notices, '' if @notices;
        }
    }

    # — SubjectAltName —
    if ($profile->has_subject_alt_name && scalar @{ $profile->subject_alt_name // [] }) {
        $self->__build_san_section($profile, \@config, \@sections);
    }

    # — ocsp_nocheck (fixed OID, no free text) —
    if ($profile->ocsp_nocheck) {
        push @config, '1.3.6.1.5.5.7.48.1.5=ASN1:NULL';
    }

    # — Shared extensions (AKI, AIA, IAN, custom OIDs) —
    $self->__build_shared_ext_lines($profile, \@config, \@sections);

    return unless @config > 1;
    push @config, @sections;
    return @config;
}

# Extensions for CRL profiles (shared extensions only)
sub __get_shared_extensions {
    my ($self, $section_name, $profile) = @_;

    my @config   = ("[ $section_name ]");
    my @sections;
    $self->__build_shared_ext_lines($profile, \@config, \@sections);

    return unless @config > 1;
    push @config, @sections;
    return @config;
}

# Shared extension lines: AKI, AIA, IssuerAltName, custom OIDs.
# Used by both __get_cert_extensions and __get_shared_extensions.
sub __build_shared_ext_lines {
    my ($self, $profile, $config, $sections) = @_;

    # — AuthorityKeyIdentifier —
    if (my $dto = $profile->authority_key_identifier) {
        my $crit = $dto->critical ? 'critical,' : '';
        my @parts;
        push @parts, 'keyid:always'  if $dto->keyid;
        push @parts, 'issuer:always' if $dto->issuer;
        push @$config, "authorityKeyIdentifier = $crit" . join(',', @parts)
            if @parts;
    }

    # — AuthorityInfoAccess —
    if (my $dto = $profile->authority_info_access) {
        my $crit = $dto->critical ? 'critical,' : '';
        my @aia;
        push @aia, map { 'caIssuers;URI:' . $self->_sanitize_uri($_) }
            @{ $dto->ca_issuers // [] };
        push @aia, map { 'OCSP;URI:'      . $self->_sanitize_uri($_) }
            @{ $dto->ocsp       // [] };
        push @$config, "authorityInfoAccess = $crit" . join(',', @aia) if @aia;
    }

    # — IssuerAltName —
    # RFC allows the same syntax as SAN here, but we only support the
    # "issuer:copy" shorthand for now.
    if (my $dto = $profile->issuer_alt_name) {
        my $crit = $dto->critical ? 'critical,' : '';
        push @$config, "issuerAltName = ${crit}issuer:copy";
    }

    # — Custom OIDs —
    # The EV OIDs have been in OpenSSL since 1.0.2 so they no longer need
    # to be injected here. This loop handles arbitrary additional OIDs only.
    for my $dto (sort { $a->oid cmp $b->oid } @{ $profile->custom_oids }) {
        unless ($self->_is_valid_oid($dto->oid)) {
            CTX('log')->application()->warn(
                "Skipping custom OID with invalid format: " . ($dto->oid // ''));
            next;
        }
        my $val = $dto->get_config_line;
        push @$config, $self->_sanitize_value($val);
        if ($dto->is_sequence) {
            push @$sections,
                '# Section for OID ' . $dto->oid,
                '[' . $dto->get_section_name . ']';

            for my $line ( $dto->get_section_lines->@*) {
                push @$sections, $self->_sanitize_value($line);
            }
        }
    }
}

# Build the subjectAltName extension lines and supporting sections.
sub __build_san_section {
    my ($self, $profile, $config, $sections) = @_;

    my @tmp_array;
    my %san_idx;

    for my $san (@{ $profile->subject_alt_name }) {
        my $type    = $san->type;
        my $sectidx = ++$san_idx{$type};

        if ($san->isa('OpenXPKI::Crypt::SubjectAltName::DirName')) {
            # ParsedDN: [ [ [attr, val], ... ], ... ]
            # CAVEAT: ParsedDN has the most significant item (usually commonName)
            # at position 0 but we need the least significant first in the config
            my @sec = ("[dirname_sect_${sectidx}]");
            my $rdnidx = 0;
            for my $rdn (reverse @{ $san->value }) {
                my ($first, @rest) = @$rdn;
                push @sec, $rdnidx++ . '.'
                    . $first->[0] . '="'
                    . $self->_sanitize_value($first->[1]) . '"';
                push @sec, map {
                    '+' . $_->[0] . '="' . $self->_sanitize_value($_->[1]) . '"'
                } @rest;
            }
            push @$sections, '', @sec;
            push @tmp_array, "dirName.${sectidx}=dirname_sect_${sectidx}";

        } elsif ($san->isa('OpenXPKI::Crypt::SubjectAltName::OtherName')) {

            my $oid = $san->oid;
            # Items are typed already so this should never happen
            unless ($self->_is_valid_oid($oid)) {
                CTX('log')->application()->warn(
                    "Skipping otherName SAN with invalid OID: $oid");
                next;
            }

            push @tmp_array, sprintf 'otherName.%d=%s;%s',
                $sectidx, $oid, $self->_sanitize_value($san->value);

        } elsif ($san->isa('OpenXPKI::Crypt::SubjectAltName::RID')) {

            # RID is of type OID so this should never happen
            unless ($self->_is_valid_oid($san->value)) {
                CTX('log')->application()->warn(
                    "Skipping OID SAN with invalid OID: "
                    . $san->value);
                next;
            }
            # Important! No quotes here
            push @tmp_array, sprintf '%s.%01d=%s',
                $type, $sectidx, $san->value;

        } else {
            # DNS, email, IP, URI — scalar values
            push @tmp_array, sprintf '%s.%01d="%s"',
                $type, $sectidx, $self->_sanitize_value($san->value);
        }
    }

    if (@tmp_array) {
        push @$config, 'subjectAltName=\@san_section';
        push @$sections, '# SAN Sections', '[san_section]', @tmp_array, '';
    }
}

################################
##     Request section        ##
################################

sub __get_req_section
{
    ##! 4: "start"
    my $self = shift;

    my @req_dn = $self->__get_subject_dn();

    @req_dn = ('[ req_distinguished_name ]', 'domainComponent = optional')
        unless @req_dn;

    my $profile = $self->{PROFILE};
    my @req_ext;
    if ($profile && $profile->has_subject_alt_name
            && scalar @{ $profile->subject_alt_name // [] }) {
        my (@ext_lines, @ext_sections);
        $self->__build_san_section($profile, \@ext_lines, \@ext_sections);
        @req_ext = ('[ req_ext ]', @ext_lines, @ext_sections) if @ext_lines;
    }

    return ('[ req ]',
        'utf8 = yes',
        'string_mask = utf8only',
        'prompt = no',
        'distinguished_name = req_distinguished_name',
        (@req_ext ? "req_extensions = req_ext" : ''),
        @req_dn,
        @req_ext
    );
}

sub __get_subject_dn
{
    ##! 4: "start"
    my $self = shift;

    return unless($self->{PROFILE});

    my $subject = $self->{PROFILE}->get_subject();
    return unless($subject);

    if (!ref $subject) {
        my @rdnlist = OpenXPKI::DN->new( $subject )->get_parsed();
        $subject = [reverse @rdnlist];
    }

    my @tmp_array = ('[ req_distinguished_name ]');
    # OpenSSL strips any leading digit+dot from attribute names, so using a
    # running integer prefix gives us a unique key for each RDN component
    # without influencing the actual attribute type written into the config.
    my $rdnidx = 0;
    foreach my $rdn (@{$subject}) {
        my @item = @$rdn;
        my $first = shift @item;
        push @tmp_array, sprintf '%01d.%s = "%s"',
            $rdnidx++, $first->[0], $self->_sanitize_value($first->[1]);
        push @tmp_array, map {
            sprintf '+%s = "%s"', $_->[0], $self->_sanitize_value($_->[1]);
        } @item if (@item);
    }

    return unless(scalar @tmp_array > 1);

    return @tmp_array;
}


sub get_config_filename
{
    my $self = shift;
    return $self->{FILENAME}->{CONFIG};
}

#####################
##     cleanup     ##
#####################

sub cleanup
{
    ##! 1: "start"
    my $self = shift;

    delete $self->{PROFILE} if (exists $self->{PROFILE});
    delete $self->{INDEX_TXT} if (exists $self->{INDEX_TXT});

    $self->__cleanup_files();

    ##! 1: "end"
    return 1;
}

sub __cleanup_files
{
    ##! 1: "start"
    my $self = shift;

    if ($self->{CONFDIR}) {
        delete $self->{CONFDIR};
    }
    if ($self->{FU}) {
        delete $self->{FU};
    }
    delete $self->{FILENAME};

    ##! 1: "end"
    return 1;
}

1;
__END__

=head1 Name

OpenXPKI::Crypto::Backend::OpenSSL::Config

=head1 Description

This module creates an OpenSSL configuration on the fly for the various
operations of OpenXPKI.

For certificate and CRL signing it consumes L<OpenXPKI::Crypt::Profile::Certificate>
and L<OpenXPKI::Crypt::Profile::CRL> directly, reading typed DTO attributes
without any intermediate shim layer.

For PKCS#10 creation L<OpenXPKI::Crypt::Profile::CSR> is handled via the same
typed DTO path as Certificate profiles; SAN entries are written by
C<__build_san_section>.

All string values from profile data are sanitised before being written into
the configuration to prevent OpenSSL config injection attacks.

=head1 Functions

=over

=item - new

=item - set_engine

=item - set_profile

=item - set_crl_items

This method prepares the OpenSSL-specific representation of the certificate
database (index.txt). The method expects an arrayref containing a list
of all certificates to revoke.

Each item in the array must be an array with one or more elements:

=over

=item * certificate serial number, either binary or as hex prefixed with 0x

=item * time of revocation (epoch)

=item * reason_code

=item * time of invalidity (epoch)

=back

=item - dump

=item - get_config_filename

=back

=head1 See Also

L<OpenXPKI::Crypt::Profile>, L<OpenXPKI::Crypt::Profile::Certificate>,
L<OpenXPKI::Crypt::Profile::CRL>, L<OpenXPKI::Crypto::Backend::OpenSSL>

=cut
