#!/bin/sh
#
# OpenXPKI (Re)configuration script
#
# Written by Martin Bartosch for the OpenXPKI project 2006
# Copyright (c) 2006 by The OpenXPKI Project
# $Revision: 80 $
#

SYSCONFDIR="[% dir.sysconfdir %]"
CFG="[% dir.bindir %]/openxpki-metaconf --config $SYSCONFDIR/openxpki.conf"
TEMPLATEDIR="$SYSCONFDIR/templates"
TEMPLATE="default"

INTERACTIVE=1
FORCE=""

reconfigure() {
    # interactively create initial configuration
    $CFG --sectionsmenu --interactive --force --writecfg $SYSCONFDIR/openxpki.conf
    return $?
}

write_config() {
    echo
    echo "Creating configuration files in $SYSCONFDIR"
    for xmlfile in $* ; do
	basename=`basename $xmlfile`
	echo -n "$basename... "
	$CFG --file $xmlfile $FORCE --dstdir $SYSCONFDIR
	if [ $? = 0 ] ; then
	    echo "done"
	else
	    echo "FAILED"
	    echo "*** Configuration incomplete (and probably broken)."
	    echo "*** Please correct the problem and repeat."
	    exit 1
	fi
    done
}


###########################################################################
echo
echo "OpenXPKI (Re)configuration Script"
echo "Copyright (c) 2006 by The OpenXPKI Project"
echo

while [ -n "$1" ] ; do
    case "$1" in
	--batch)
	    echo "Entering batch mode..."
	    INTERACTIVE=0
	    shift
	    ;;
	--force)
	    FORCE="$1"
	    shift
	    ;;
	*)
	    echo "Usage: $0 OPTIONS"
	    echo "Options:"
	    echo "  --batch    Noninteractively reconfigure XML files from openxpki.conf"
	    exit 0;
	    ;;
    esac
done

if [ "$INTERACTIVE" = "1" ] ; then
    if ! reconfigure ; then
	echo "Exiting..."
	exit 0
    fi
fi

XMLSTYLE="`$CFG --getcfg deployment.xmlstyle `"

FILES="$TEMPLATEDIR/$TEMPLATE/log.conf"

case $XMLSTYLE in
    multi-file)
	echo "Creating configuration (multiple XML files)..."
	FILES="$FILES `ls $TEMPLATEDIR/$TEMPLATE/*.xml`"
	;;
    all-in-one)
	echo "Creating configuration (single XML file)..."
	FILES="$FILES $TEMPLATEDIR/$TEMPLATE/config.xml"
	;;
    *)
	echo "Illegal deployment mode $XMLSTYLE"
	exit 1
	;;
esac

write_config $FILES

