--- #YAML:1.0
name:                Bundle-OpenXPKI
version:             0.03
abstract:            A bundle to install modules required for OpenXPKI
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Alexander Klink <alech@cpan.org>
