## Written 2013 by Scott Hardin for the OpenXPKI project
## Copyright (C) 2013 by The OpenXPKI Project

SRCNAME		:= enrollment
SRCBASE		=  $(TOPDIR)/clients/perl/OpenXPKI-Client-Enrollment

include ../openxpki-perldeps-core/Makefile


