id: CN
label: CN
description: I18N_OPENXPKI_UI_PROFILE_CN_DESC
type: freetext
source: CN:(.+)
width: 60
id: O
label: O
description: I18N_OPENXPKI_UI_PROFILE_O_DESC
type: freetext
source: O:(.+)
width: 40
